version: "3.9"
services:
  registry:
    container_name: docker-registry
    image: registry:2.6.2
    volumes:
      - ./registry-data:/var/lib/registry
    ports:
      - "5000:5000"
    restart: always
  ui:
    container_name: docker-ui
    image: parabuzzle/craneoperator:2.2.5
    ports:
      - 5080:80
    environment:
      - REGISTRY_HOST=docker-registry
      - REGISTRY_PORT=5000
      - REGISTRY_PROTOCOL=http
      - SSL_VERIFY=false
      - USERNAME=admin
      - PASSWORD=admin
    restart: always
    depends_on:
      - registry